### ISSUE TITLE
Triggered ?

### ISSUE THREAD

**Issue by Ritzing** [silent-lad/sentimentAnalysisVader#1]

**Comment by silent-lad** [comment]
------______________-------
                                  -yep

**Comment by Ritzing** [comment]
Good , this is worth triggering 
also look at the trello board, added an idea .. will discuss it in evening

**Comment by silent-lad** [comment]
making a api on which you can send paragraphs and get line wise sentiment analysis...kisi bhi project main daal skte he fir isko...

**Comment by Ritzing** [comment]
looks great
